```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grayghost-backup
spec:
  schedule: "0 2 * * *"  # Run at 2 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: grayghost:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  /app/deployment/scripts/backup.sh production
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: access-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: secret-key
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: grayghost-config
                      key: postgres_host
              volumeMounts:
                - name: backup-volume
                  mountPath: /backups
          volumes:
            - name: backup-volume
              emptyDir: {}
          restartPolicy: OnFailure
```